In [2]:
import json

file = open("sw_templates.json", 'r')
data = json.load(file)
data

{'access': ['switchport mode access',
  'switchport access vlan',
  'switchport nonegotiate',
  'spanning-tree portfast',
  'spanning-tree bpduguard enable'],
 'trunk': ['switchport trunk encapsulation dot1q',
  'switchport mode trunk',
  'switchport trunk native vlan 999',
  'switchport trunk allowed vlan']}

In [3]:
import pyarrow.parquet as pq

table = pq.read_table("Shuffled.parquet")
df = table.to_pandas()
df

,brand,model,fuel_type,mileage,year,owner_type,accidents,color,transmission,price,car_age
968,Lexus,GX,Gas,51271,2001,First,2,Transparent,Automatic,361263.41,22
848,Porsche,Macan,Hybrid,20254,2018,First,4,Black,Automatic,683604.60,5
974,Lexus,GX,Hybrid,55448,2009,First,0,Golden,Manual,683398.37,14
91,Audi,A6,Diesel,197300,2011,Third,2,Aquamarine,Automatic,11612.14,12
808,Volvo,XC40,Hybrid,15916,2022,First,3,Silver,Automatic,872879.46,1
...,...,...,...,...,...,...,...,...,...,...,...
772,Volvo,XC60,Hybrid,61570,2000,Third,0,Aquamarine,Automatic,203756.50,23
501,Volkswagen,Jetta,Electric,171319,2015,First,0,White,Manual,236128.14,8
165,Ford,Mustang,Hybrid,100259,2013,First,0,Blue,Automatic,1013045.09,10
680,Jeep,Compass,Gas,49482,2010,Second,4,Red,Automatic,89296.37,13
864,Porsche,Taycan,Gas,197958,2021,Second,3,Blue,Manual,9786.84,2

In [1]:
import json

file = open("sw_templates.json",'r')
json_data = json.load(file)
file.close()


json_data['access+trunk'] = ['switchport mode access',
  'switchport access vlan',
  'switchport nonegotiate',
  'spanning-tree portfast',
  'spanning-tree bpduguard enable',
  'switchport trunk encapsulation dot1q',
  'switchport mode trunk',
  'switchport trunk native vlan 999',
  'switchport trunk allowed vlan']


file = open("sw_templates.json",'w')
json.dump(json_data, file,  indent=2)
file.close()

JSONDecodeError: Expecting value: line 1 column 1 (char 0)

In [1]:
import pyarrow.parquet as pq

table = pq.read_table("Shuffled.parquet")
df = table.to_pandas()
df

,brand,model,fuel_type,mileage,year,owner_type,accidents,color,transmission,price,car_age
968,Lexus,GX,Gas,51271,2001,First,2,Transparent,Automatic,361263.41,22
848,Porsche,Macan,Hybrid,20254,2018,First,4,Black,Automatic,683604.60,5
974,Lexus,GX,Hybrid,55448,2009,First,0,Golden,Manual,683398.37,14
91,Audi,A6,Diesel,197300,2011,Third,2,Aquamarine,Automatic,11612.14,12
808,Volvo,XC40,Hybrid,15916,2022,First,3,Silver,Automatic,872879.46,1
...,...,...,...,...,...,...,...,...,...,...,...
772,Volvo,XC60,Hybrid,61570,2000,Third,0,Aquamarine,Automatic,203756.50,23
501,Volkswagen,Jetta,Electric,171319,2015,First,0,White,Manual,236128.14,8
165,Ford,Mustang,Hybrid,100259,2013,First,0,Blue,Automatic,1013045.09,10
680,Jeep,Compass,Gas,49482,2010,Second,4,Red,Automatic,89296.37,13
864,Porsche,Taycan,Gas,197958,2021,Second,3,Blue,Manual,9786.84,2

In [2]:
import pandas as pd

df = pd.read_csv("filename.csv")
df

  Country Code     country  population    square    density
0           KZ  Kazakhstan       17.04   2724902   6.253436
1           RU      Russia      143.50  17125191   8.379469
2           BY     Belarus        9.50    207600  45.761079
3           UA     Ukraine       45.50    603628  75.377550